// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Gender string

const (
	GenderMale   Gender = "male"
	GenderFemale Gender = "female"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

func (e Gender) Valid() bool {
	switch e {
	case GenderMale,
		GenderFemale:
		return true
	}
	return false
}

func AllGenderValues() []Gender {
	return []Gender{
		GenderMale,
		GenderFemale,
	}
}

type PetAggressionLevel string

const (
	PetAggressionLevelNonAggressive                            PetAggressionLevel = "Non-aggressive"
	PetAggressionLevelGuardingbehavior                         PetAggressionLevel = "Guarding behavior"
	PetAggressionLevelMildaggressionunderspecificcircumstances PetAggressionLevel = "Mild aggression under specific circumstances"
	PetAggressionLevelKnownhistoryofaggression                 PetAggressionLevel = "Known history of aggression"
)

func (e *PetAggressionLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetAggressionLevel(s)
	case string:
		*e = PetAggressionLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for PetAggressionLevel: %T", src)
	}
	return nil
}

type NullPetAggressionLevel struct {
	PetAggressionLevel PetAggressionLevel `json:"petAggressionLevel"`
	Valid              bool               `json:"valid"` // Valid is true if PetAggressionLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetAggressionLevel) Scan(value interface{}) error {
	if value == nil {
		ns.PetAggressionLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetAggressionLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetAggressionLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetAggressionLevel), nil
}

func (e PetAggressionLevel) Valid() bool {
	switch e {
	case PetAggressionLevelNonAggressive,
		PetAggressionLevelGuardingbehavior,
		PetAggressionLevelMildaggressionunderspecificcircumstances,
		PetAggressionLevelKnownhistoryofaggression:
		return true
	}
	return false
}

func AllPetAggressionLevelValues() []PetAggressionLevel {
	return []PetAggressionLevel{
		PetAggressionLevelNonAggressive,
		PetAggressionLevelGuardingbehavior,
		PetAggressionLevelMildaggressionunderspecificcircumstances,
		PetAggressionLevelKnownhistoryofaggression,
	}
}

type PetAllergy string

const (
	PetAllergyNone     PetAllergy = "None"
	PetAllergyBeef     PetAllergy = "Beef"
	PetAllergyChicken  PetAllergy = "Chicken"
	PetAllergyLamb     PetAllergy = "Lamb"
	PetAllergyPork     PetAllergy = "Pork"
	PetAllergyFish     PetAllergy = "Fish"
	PetAllergyEggs     PetAllergy = "Eggs"
	PetAllergyMilk     PetAllergy = "Milk"
	PetAllergyCheese   PetAllergy = "Cheese"
	PetAllergyBarley   PetAllergy = "Barley"
	PetAllergyWheat    PetAllergy = "Wheat"
	PetAllergyCorn     PetAllergy = "Corn"
	PetAllergySoy      PetAllergy = "Soy"
	PetAllergyPeanuts  PetAllergy = "Peanuts"
	PetAllergySesame   PetAllergy = "Sesame"
	PetAllergyMillet   PetAllergy = "Millet"
	PetAllergyRice     PetAllergy = "Rice"
	PetAllergyOats     PetAllergy = "Oats"
	PetAllergyTreeNuts PetAllergy = "Tree Nuts"
	PetAllergyYeast    PetAllergy = "Yeast"
	PetAllergyFruits   PetAllergy = "Fruits"
)

func (e *PetAllergy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetAllergy(s)
	case string:
		*e = PetAllergy(s)
	default:
		return fmt.Errorf("unsupported scan type for PetAllergy: %T", src)
	}
	return nil
}

type NullPetAllergy struct {
	PetAllergy PetAllergy `json:"petAllergy"`
	Valid      bool       `json:"valid"` // Valid is true if PetAllergy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetAllergy) Scan(value interface{}) error {
	if value == nil {
		ns.PetAllergy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetAllergy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetAllergy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetAllergy), nil
}

func (e PetAllergy) Valid() bool {
	switch e {
	case PetAllergyNone,
		PetAllergyBeef,
		PetAllergyChicken,
		PetAllergyLamb,
		PetAllergyPork,
		PetAllergyFish,
		PetAllergyEggs,
		PetAllergyMilk,
		PetAllergyCheese,
		PetAllergyBarley,
		PetAllergyWheat,
		PetAllergyCorn,
		PetAllergySoy,
		PetAllergyPeanuts,
		PetAllergySesame,
		PetAllergyMillet,
		PetAllergyRice,
		PetAllergyOats,
		PetAllergyTreeNuts,
		PetAllergyYeast,
		PetAllergyFruits:
		return true
	}
	return false
}

func AllPetAllergyValues() []PetAllergy {
	return []PetAllergy{
		PetAllergyNone,
		PetAllergyBeef,
		PetAllergyChicken,
		PetAllergyLamb,
		PetAllergyPork,
		PetAllergyFish,
		PetAllergyEggs,
		PetAllergyMilk,
		PetAllergyCheese,
		PetAllergyBarley,
		PetAllergyWheat,
		PetAllergyCorn,
		PetAllergySoy,
		PetAllergyPeanuts,
		PetAllergySesame,
		PetAllergyMillet,
		PetAllergyRice,
		PetAllergyOats,
		PetAllergyTreeNuts,
		PetAllergyYeast,
		PetAllergyFruits,
	}
}

type PetBehavior string

const (
	PetBehaviorObedient   PetBehavior = "Obedient"
	PetBehaviorStubborn   PetBehavior = "Stubborn"
	PetBehaviorCurious    PetBehavior = "Curious"
	PetBehaviorAlert      PetBehavior = "Alert"
	PetBehaviorRelaxed    PetBehavior = "Relaxed"
	PetBehaviorAnxious    PetBehavior = "Anxious"
	PetBehaviorFearful    PetBehavior = "Fearful"
	PetBehaviorConfident  PetBehavior = "Confident"
	PetBehaviorAggressive PetBehavior = "Aggressive"
	PetBehaviorTimid      PetBehavior = "Timid"
	PetBehaviorDominant   PetBehavior = "Dominant"
	PetBehaviorSubmissive PetBehavior = "Submissive"
)

func (e *PetBehavior) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetBehavior(s)
	case string:
		*e = PetBehavior(s)
	default:
		return fmt.Errorf("unsupported scan type for PetBehavior: %T", src)
	}
	return nil
}

type NullPetBehavior struct {
	PetBehavior PetBehavior `json:"petBehavior"`
	Valid       bool        `json:"valid"` // Valid is true if PetBehavior is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetBehavior) Scan(value interface{}) error {
	if value == nil {
		ns.PetBehavior, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetBehavior.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetBehavior) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetBehavior), nil
}

func (e PetBehavior) Valid() bool {
	switch e {
	case PetBehaviorObedient,
		PetBehaviorStubborn,
		PetBehaviorCurious,
		PetBehaviorAlert,
		PetBehaviorRelaxed,
		PetBehaviorAnxious,
		PetBehaviorFearful,
		PetBehaviorConfident,
		PetBehaviorAggressive,
		PetBehaviorTimid,
		PetBehaviorDominant,
		PetBehaviorSubmissive:
		return true
	}
	return false
}

func AllPetBehaviorValues() []PetBehavior {
	return []PetBehavior{
		PetBehaviorObedient,
		PetBehaviorStubborn,
		PetBehaviorCurious,
		PetBehaviorAlert,
		PetBehaviorRelaxed,
		PetBehaviorAnxious,
		PetBehaviorFearful,
		PetBehaviorConfident,
		PetBehaviorAggressive,
		PetBehaviorTimid,
		PetBehaviorDominant,
		PetBehaviorSubmissive,
	}
}

type PetBreed string

const (
	PetBreedAustralianShepherd             PetBreed = "Australian Shepherd"
	PetBreedAmericanCockerSpaniel          PetBreed = "American Cocker Spaniel"
	PetBreedAkita                          PetBreed = "Akita"
	PetBreedAustralianCattle               PetBreed = "Australian Cattle"
	PetBreedAiredaleTerrier                PetBreed = "Airedale Terrier"
	PetBreedAlaskanMalamute                PetBreed = "Alaskan Malamute"
	PetBreedAmericanStaffordshireTerrier   PetBreed = "American Staffordshire Terrier"
	PetBreedAnatolianShepherd              PetBreed = "Anatolian Shepherd"
	PetBreedAmericanEskimo                 PetBreed = "American Eskimo"
	PetBreedAfghanHound                    PetBreed = "Afghan Hound"
	PetBreedAmericanHairlessTerrier        PetBreed = "American Hairless Terrier"
	PetBreedAustralianTerrier              PetBreed = "Australian Terrier"
	PetBreedAmericanWaterSpaniel           PetBreed = "American Water Spaniel"
	PetBreedAffenpinscher                  PetBreed = "Affenpinscher"
	PetBreedAmericanEnglishCoonhound       PetBreed = "American English Coonhound"
	PetBreedAmericanFoxhound               PetBreed = "American Foxhound"
	PetBreedAzawakh                        PetBreed = "Azawakh"
	PetBreedAmericanPitBullTerrier         PetBreed = "American Pit Bull Terrier"
	PetBreedAmericanWhiteShepherd          PetBreed = "American White Shepherd"
	PetBreedAlapahaBlueBloodBulldog        PetBreed = "Alapaha Blue Blood Bulldog"
	PetBreedAlaskanKleeKai                 PetBreed = "Alaskan Klee Kai"
	PetBreedAppenzellerSennenhund          PetBreed = "Appenzeller Sennenhund"
	PetBreedAustralianBulldog              PetBreed = "Australian Bulldog"
	PetBreedAustralianKelpie               PetBreed = "Australian Kelpie"
	PetBreedAustralianStumpyTailCattle     PetBreed = "Australian Stumpy Tail Cattle"
	PetBreedAustrianBlackandTanHound       PetBreed = "Austrian Black and Tan Hound"
	PetBreedAustrianPinscher               PetBreed = "Austrian Pinscher"
	PetBreedAlaskanHusky                   PetBreed = "Alaskan Husky"
	PetBreedAmericanBulldog                PetBreed = "American Bulldog"
	PetBreedAndalusianHound                PetBreed = "Andalusian Hound"
	PetBreedAmericanMastiff                PetBreed = "American Mastiff"
	PetBreedAkbash                         PetBreed = "Akbash"
	PetBreedAlanoEspanol                   PetBreed = "Alano Espanol"
	PetBreedAriegePointer                  PetBreed = "Ariege Pointer"
	PetBreedAriegeois                      PetBreed = "Ariegeois"
	PetBreedAfricanis                      PetBreed = "Africanis"
	PetBreedAidi                           PetBreed = "Aidi"
	PetBreedAmericanStaghound              PetBreed = "American Staghound"
	PetBreedAlopekis                       PetBreed = "Alopekis"
	PetBreedBulldog                        PetBreed = "Bulldog"
	PetBreedBeagle                         PetBreed = "Beagle"
	PetBreedBoxer                          PetBreed = "Boxer"
	PetBreedBostonTerrier                  PetBreed = "Boston Terrier"
	PetBreedBerneseMountain                PetBreed = "Bernese Mountain"
	PetBreedBrittany                       PetBreed = "Brittany"
	PetBreedBorderCollie                   PetBreed = "Border Collie"
	PetBreedBassetHound                    PetBreed = "Basset Hound"
	PetBreedBelgianMalinois                PetBreed = "Belgian Malinois"
	PetBreedBichonFrise                    PetBreed = "Bichon Frise"
	PetBreedBloodhound                     PetBreed = "Bloodhound"
	PetBreedBullmastiff                    PetBreed = "Bullmastiff"
	PetBreedBullTerrier                    PetBreed = "Bull Terrier"
	PetBreedBasenji                        PetBreed = "Basenji"
	PetBreedBoykinSpaniel                  PetBreed = "Boykin Spaniel"
	PetBreedBrusselsGriffon                PetBreed = "Brussels Griffon"
	PetBreedBouvierdesFlandres             PetBreed = "Bouvier des Flandres"
	PetBreedBorderTerrier                  PetBreed = "Border Terrier"
	PetBreedBorzoi                         PetBreed = "Borzoi"
	PetBreedBelgianTervuren                PetBreed = "Belgian Tervuren"
	PetBreedBelgianSheep                   PetBreed = "Belgian Sheep"
	PetBreedBeauceron                      PetBreed = "Beauceron"
	PetBreedBoerboel                       PetBreed = "Boerboel"
	PetBreedBeardedCollie                  PetBreed = "Bearded Collie"
	PetBreedBlackRussianTerrier            PetBreed = "Black Russian Terrier"
	PetBreedBlackandTanCoonhound           PetBreed = "Black and Tan Coonhound"
	PetBreedBluetickCoonhound              PetBreed = "Bluetick Coonhound"
	PetBreedBedlingtonTerrier              PetBreed = "Bedlington Terrier"
	PetBreedBarbet                         PetBreed = "Barbet"
	PetBreedBriard                         PetBreed = "Briard"
	PetBreedBergerPicard                   PetBreed = "Berger Picard"
	PetBreedBergamasco                     PetBreed = "Bergamasco"
	PetBreedBolognese                      PetBreed = "Bolognese"
	PetBreedBassetBleudeGascogne           PetBreed = "Basset Bleu de Gascogne"
	PetBreedBassetFauvedeBretagne          PetBreed = "Basset Fauve de Bretagne"
	PetBreedBelgianShepherdLaekenois       PetBreed = "Belgian Shepherd Laekenois"
	PetBreedBlackMouthCur                  PetBreed = "Black Mouth Cur"
	PetBreedBlackNorwegianElkhound         PetBreed = "Black Norwegian Elkhound"
	PetBreedBlueLacy                       PetBreed = "Blue Lacy"
	PetBreedBluePicardySpaniel             PetBreed = "Blue Picardy Spaniel"
	PetBreedBohemianShepherd               PetBreed = "Bohemian Shepherd"
	PetBreedBraccoItaliano                 PetBreed = "Bracco Italiano"
	PetBreedBraqueduBourbonnais            PetBreed = "Braque du Bourbonnais"
	PetBreedBrazilianTerrier               PetBreed = "Brazilian Terrier"
	PetBreedBulgarianShepherd              PetBreed = "Bulgarian Shepherd"
	PetBreedBassetArtesienNormand          PetBreed = "Basset Artesien Normand"
	PetBreedBroholmer                      PetBreed = "Broholmer"
	PetBreedBiewerTerrier                  PetBreed = "Biewer Terrier"
	PetBreedBriquetGriffonVendeen          PetBreed = "Briquet Griffon Vendeen"
	PetBreedBukovinaSheepdog               PetBreed = "Bukovina Sheepdog"
	PetBreedBeagleHarrier                  PetBreed = "Beagle-Harrier"
	PetBreedBeaglier                       PetBreed = "Beaglier"
	PetBreedBavarianMountainHound          PetBreed = "Bavarian Mountain Hound"
	PetBreedBouvierdesArdennes             PetBreed = "Bouvier des Ardennes"
	PetBreedBullArab                       PetBreed = "Bull Arab"
	PetBreedCavalierKingCharlesSpaniel     PetBreed = "Cavalier King Charles Spaniel"
	PetBreedCaneCorso                      PetBreed = "Cane Corso"
	PetBreedChihuahua                      PetBreed = "Chihuahua"
	PetBreedCollie                         PetBreed = "Collie"
	PetBreedChesapeakeBayRetriever         PetBreed = "Chesapeake Bay Retriever"
	PetBreedCardiganWelshCorgi             PetBreed = "Cardigan Welsh Corgi"
	PetBreedCairnTerrier                   PetBreed = "Cairn Terrier"
	PetBreedChineseCrested                 PetBreed = "Chinese Crested"
	PetBreedCotonDeTulear                  PetBreed = "Coton De Tulear"
	PetBreedChowChow                       PetBreed = "Chow Chow"
	PetBreedClumberSpaniel                 PetBreed = "Clumber Spaniel"
	PetBreedCurlyCoatedRetriever           PetBreed = "Curly-Coated Retriever"
	PetBreedCirnecodellEtna                PetBreed = "Cirneco dell’Etna"
	PetBreedCanaan                         PetBreed = "Canaan"
	PetBreedChinook                        PetBreed = "Chinook"
	PetBreedCeskyTerrier                   PetBreed = "Cesky Terrier"
	PetBreedCockapoo                       PetBreed = "Cockapoo"
	PetBreedCanadianEskimo                 PetBreed = "Canadian Eskimo"
	PetBreedCarolina                       PetBreed = "Carolina"
	PetBreedCarpathianSheepdog             PetBreed = "Carpathian Sheepdog"
	PetBreedCatahoulaBulldog               PetBreed = "Catahoula Bulldog"
	PetBreedCatahoulaLeopard               PetBreed = "Catahoula Leopard"
	PetBreedCatalanSheepdog                PetBreed = "Catalan Sheepdog"
	PetBreedCaucasianOvcharka              PetBreed = "Caucasian Ovcharka"
	PetBreedCentralAsianOvtcharka          PetBreed = "Central Asian Ovtcharka"
	PetBreedCroatianSheepdog               PetBreed = "Croatian Sheepdog"
	PetBreedCzechoslovakianWolfdog         PetBreed = "Czechoslovakian Wolfdog"
	PetBreedCeskyFousek                    PetBreed = "Cesky Fousek"
	PetBreedChartPolski                    PetBreed = "Chart Polski"
	PetBreedCairmal                        PetBreed = "Cairmal"
	PetBreedChorkie                        PetBreed = "Chorkie"
	PetBreedCockalier                      PetBreed = "Cockalier"
	PetBreedCaravanHound                   PetBreed = "Caravan Hound"
	PetBreedCodaSerradeAires               PetBreed = "Cão da Serra de Aires"
	PetBreedChippiparai                    PetBreed = "Chippiparai"
	PetBreedChizer                         PetBreed = "Chizer"
	PetBreedCotonese                       PetBreed = "Cotonese"
	PetBreedDachshund                      PetBreed = "Dachshund"
	PetBreedDobermanPinscher               PetBreed = "Doberman Pinscher"
	PetBreedDalmatian                      PetBreed = "Dalmatian"
	PetBreedDoguedeBordeaux                PetBreed = "Dogue de Bordeaux"
	PetBreedDogoArgentino                  PetBreed = "Dogo Argentino"
	PetBreedDandieDinmontTerrier           PetBreed = "Dandie Dinmont Terrier"
	PetBreedDutchShepherd                  PetBreed = "Dutch Shepherd"
	PetBreedDoubleDoodle                   PetBreed = "Double Doodle"
	PetBreedDeutscheBracke                 PetBreed = "Deutsche Bracke"
	PetBreedDorkie                         PetBreed = "Dorkie"
	PetBreedDanishSwedishFarmdog           PetBreed = "Danish-Swedish Farmdog"
	PetBreedDingo                          PetBreed = "Dingo"
	PetBreedDutchSmoushond                 PetBreed = "Dutch Smoushond"
	PetBreedDrentsePatrijshond             PetBreed = "Drentse Patrijshond"
	PetBreedDrever                         PetBreed = "Drever"
	PetBreedDunker                         PetBreed = "Dunker"
	PetBreedDorgi                          PetBreed = "Dorgi"
	PetBreedEnglishSpringerSpaniel         PetBreed = "English Springer Spaniel"
	PetBreedEnglishCockerSpaniel           PetBreed = "English Cocker Spaniel"
	PetBreedEnglishSetter                  PetBreed = "English Setter"
	PetBreedEnglishToySpaniel              PetBreed = "English Toy Spaniel"
	PetBreedEntlebucherMountain            PetBreed = "Entlebucher Mountain"
	PetBreedEnglishFoxhound                PetBreed = "English Foxhound"
	PetBreedEastEuropeanShepherd           PetBreed = "East-European Shepherd"
	PetBreedEnglishShepherd                PetBreed = "English Shepherd"
	PetBreedEurasier                       PetBreed = "Eurasier"
	PetBreedEastSiberianLaika              PetBreed = "East Siberian Laika"
	PetBreedFrenchBulldog                  PetBreed = "French Bulldog"
	PetBreedFlatCoatedRetriever            PetBreed = "Flat-Coated Retriever"
	PetBreedFieldSpaniel                   PetBreed = "Field Spaniel"
	PetBreedFinnishLapphund                PetBreed = "Finnish Lapphund"
	PetBreedFinnishSpitz                   PetBreed = "Finnish Spitz"
	PetBreedFilaBrasileiro                 PetBreed = "Fila Brasileiro"
	PetBreedFrenchSpaniel                  PetBreed = "French Spaniel"
	PetBreedFinnishHound                   PetBreed = "Finnish Hound"
	PetBreedFrancaisBlancetNoir            PetBreed = "Francais Blanc et Noir"
	PetBreedGermanShepherd                 PetBreed = "German Shepherd"
	PetBreedGoldenRetriever                PetBreed = "Golden Retriever"
	PetBreedGermanShorthairedPointer       PetBreed = "German Shorthaired Pointer"
	PetBreedGreatDane                      PetBreed = "Great Dane"
	PetBreedGermanWirehairedPointer        PetBreed = "German Wirehaired Pointer"
	PetBreedGiantSchnauzer                 PetBreed = "Giant Schnauzer"
	PetBreedGreatPyrenees                  PetBreed = "Great Pyrenees"
	PetBreedGreaterSwissMountain           PetBreed = "Greater Swiss Mountain"
	PetBreedGordonSetter                   PetBreed = "Gordon Setter"
	PetBreedGermanPinscher                 PetBreed = "German Pinscher"
	PetBreedGreyhound                      PetBreed = "Greyhound"
	PetBreedGlenofImaalTerrier             PetBreed = "Glen of Imaal Terrier"
	PetBreedGrandBassetGriffonVendeen      PetBreed = "Grand Basset Griffon Vendeen"
	PetBreedGoldendoodle                   PetBreed = "Goldendoodle"
	PetBreedGermanLonghairedPointer        PetBreed = "German Longhaired Pointer"
	PetBreedGreenland                      PetBreed = "Greenland"
	PetBreedGriffonbleudeGascogne          PetBreed = "Griffon bleu de Gascogne"
	PetBreedGrandBleudeGascogne            PetBreed = "Grand Bleu de Gascogne"
	PetBreedHavanese                       PetBreed = "Havanese"
	PetBreedHarrier                        PetBreed = "Harrier"
	PetBreedHokkaido                       PetBreed = "Hokkaido"
	PetBreedHovawart                       PetBreed = "Hovawart"
	PetBreedHamiltonHound                  PetBreed = "Hamilton Hound"
	PetBreedItalianGreyhound               PetBreed = "Italian Greyhound"
	PetBreedIrishWolfhound                 PetBreed = "Irish Wolfhound"
	PetBreedIrishSetter                    PetBreed = "Irish Setter"
	PetBreedIrishTerrier                   PetBreed = "Irish Terrier"
	PetBreedIcelandicSheepdog              PetBreed = "Icelandic Sheepdog"
	PetBreedIrishRedandWhiteSetter         PetBreed = "Irish Red and White Setter"
	PetBreedIbizanHound                    PetBreed = "Ibizan Hound"
	PetBreedIrishWaterSpaniel              PetBreed = "Irish Water Spaniel"
	PetBreedJackRussellTerrier             PetBreed = "Jack Russell Terrier"
	PetBreedJapaneseChin                   PetBreed = "Japanese Chin"
	PetBreedJapaneseSpitz                  PetBreed = "Japanese Spitz"
	PetBreedJagdterrier                    PetBreed = "Jagdterrier"
	PetBreedJapaneseTerrier                PetBreed = "Japanese Terrier"
	PetBreedJmthund                        PetBreed = "Jämthund"
	PetBreedKeeshond                       PetBreed = "Keeshond"
	PetBreedKerryBlueTerrier               PetBreed = "Kerry Blue Terrier"
	PetBreedKooikerhondje                  PetBreed = "Kooikerhondje"
	PetBreedKuvasz                         PetBreed = "Kuvasz"
	PetBreedKomondor                       PetBreed = "Komondor"
	PetBreedKoreanJindo                    PetBreed = "Korean Jindo"
	PetBreedKarelianBear                   PetBreed = "Karelian Bear"
	PetBreedKishuKen                       PetBreed = "Kishu Ken"
	PetBreedKoolie                         PetBreed = "Koolie"
	PetBreedKromfohrlander                 PetBreed = "Kromfohrlander"
	PetBreedKangal                         PetBreed = "Kangal"
	PetBreedKingShepherd                   PetBreed = "King Shepherd"
	PetBreedKyiLeo                         PetBreed = "Kyi-Leo"
	PetBreedKarstShepherd                  PetBreed = "Karst Shepherd"
	PetBreedLabradorRetriever              PetBreed = "Labrador Retriever"
	PetBreedLhasaApso                      PetBreed = "Lhasa Apso"
	PetBreedLagottoRomagnolo               PetBreed = "Lagotto Romagnolo"
	PetBreedLeonberger                     PetBreed = "Leonberger"
	PetBreedLakelandTerrier                PetBreed = "Lakeland Terrier"
	PetBreedLowchen                        PetBreed = "Lowchen"
	PetBreedLargeMunsterlander             PetBreed = "Large Munsterlander"
	PetBreedLancashireHeeler               PetBreed = "Lancashire Heeler"
	PetBreedLandseer                       PetBreed = "Landseer"
	PetBreedLucasTerrier                   PetBreed = "Lucas Terrier"
	PetBreedLurcher                        PetBreed = "Lurcher"
	PetBreedLapponianHerder                PetBreed = "Lapponian Herder"
	PetBreedMiniatureSchnauzer             PetBreed = "Miniature Schnauzer"
	PetBreedMiniatureAmericanShepherd      PetBreed = "Miniature American Shepherd"
	PetBreedMastiff                        PetBreed = "Mastiff"
	PetBreedMaltese                        PetBreed = "Maltese"
	PetBreedMiniaturePinscher              PetBreed = "Miniature Pinscher"
	PetBreedMiniatureBullTerrier           PetBreed = "Miniature Bull Terrier"
	PetBreedManchesterTerrier              PetBreed = "Manchester Terrier"
	PetBreedMiniatureBulldog               PetBreed = "Miniature Bulldog"
	PetBreedMiniaturePoodle                PetBreed = "Miniature Poodle"
	PetBreedMiniatureSharPei               PetBreed = "Miniature Shar Pei"
	PetBreedMcNab                          PetBreed = "McNab"
	PetBreedMudi                           PetBreed = "Mudi"
	PetBreedMountainFeist                  PetBreed = "Mountain Feist"
	PetBreedMaremmaSheepdog                PetBreed = "Maremma Sheepdog"
	PetBreedMalShi                         PetBreed = "Mal-Shi"
	PetBreedMoscowWatchdog                 PetBreed = "Moscow Watchdog"
	PetBreedMountainCur                    PetBreed = "Mountain Cur"
	PetBreedMajesticTreeHound              PetBreed = "Majestic Tree Hound"
	PetBreedNewfoundland                   PetBreed = "Newfoundland"
	PetBreedNovaScotiaDuckTollingRetriever PetBreed = "Nova Scotia Duck Tolling Retriever"
	PetBreedNorwegianElkhound              PetBreed = "Norwegian Elkhound"
	PetBreedNeapolitanMastiff              PetBreed = "Neapolitan Mastiff"
	PetBreedNorwichTerrier                 PetBreed = "Norwich Terrier"
	PetBreedNorfolkTerrier                 PetBreed = "Norfolk Terrier"
	PetBreedNorwegianBuhund                PetBreed = "Norwegian Buhund"
	PetBreedNorwegianLundehund             PetBreed = "Norwegian Lundehund"
	PetBreedNorrbottenspets                PetBreed = "Norrbottenspets"
	PetBreedNorthernInuit                  PetBreed = "Northern Inuit"
	PetBreedNewGuineaSinging               PetBreed = "New Guinea Singing"
	PetBreedOldEnglishSheepdog             PetBreed = "Old English Sheepdog"
	PetBreedOtterhound                     PetBreed = "Otterhound"
	PetBreedOldeEnglishBulldogge           PetBreed = "Olde English Bulldogge"
	PetBreedPoodle                         PetBreed = "Poodle"
	PetBreedPembrokeWelshCorgi             PetBreed = "Pembroke Welsh Corgi"
	PetBreedPomeranian                     PetBreed = "Pomeranian"
	PetBreedPug                            PetBreed = "Pug"
	PetBreedPortugueseWater                PetBreed = "Portuguese Water"
	PetBreedPapillon                       PetBreed = "Papillon"
	PetBreedPekingese                      PetBreed = "Pekingese"
	PetBreedParsonRussellTerrier           PetBreed = "Parson Russell Terrier"
	PetBreedPointer                        PetBreed = "Pointer"
	PetBreedPuli                           PetBreed = "Puli"
	PetBreedPumi                           PetBreed = "Pumi"
	PetBreedPortuguesePodengoPequeno       PetBreed = "Portuguese Podengo Pequeno"
	PetBreedPetitBassetGriffonVendeen      PetBreed = "Petit Basset Griffon Vendeen"
	PetBreedPlottHound                     PetBreed = "Plott Hound"
	PetBreedPolishLowlandSheepdog          PetBreed = "Polish Lowland Sheepdog"
	PetBreedPharaohHound                   PetBreed = "Pharaoh Hound"
	PetBreedPyreneanShepherd               PetBreed = "Pyrenean Shepherd"
	PetBreedPakistaniMastiff               PetBreed = "Pakistani Mastiff"
	PetBreedPatterdaleTerrier              PetBreed = "Patterdale Terrier"
	PetBreedPerrodePresaCanario            PetBreed = "Perro de Presa Canario"
	PetBreedPerrodePresaMallorquin         PetBreed = "Perro de Presa Mallorquin"
	PetBreedPeruvianIncaOrchid             PetBreed = "Peruvian Inca Orchid"
	PetBreedPicardySpaniel                 PetBreed = "Picardy Spaniel"
	PetBreedPrazskyKrysarik                PetBreed = "Prazsky Krysarik"
	PetBreedPontAudemerSpaniel             PetBreed = "Pont-Audemer Spaniel"
	PetBreedPyreneanMastiff                PetBreed = "Pyrenean Mastiff"
	PetBreedPolishTatraSheepdog            PetBreed = "Polish Tatra Sheepdog"
	PetBreedPuggle                         PetBreed = "Puggle"
	PetBreedPudelpointer                   PetBreed = "Pudelpointer"
	PetBreedPlummerTerrier                 PetBreed = "Plummer Terrier"
	PetBreedPortuguesePointer              PetBreed = "Portuguese Pointer"
	PetBreedPolishHuntingDog               PetBreed = "Polish Hunting Dog"
	PetBreedRottweiler                     PetBreed = "Rottweiler"
	PetBreedRhodesianRidgeback             PetBreed = "Rhodesian Ridgeback"
	PetBreedRatTerrier                     PetBreed = "Rat Terrier"
	PetBreedRedboneCoonhound               PetBreed = "Redbone Coonhound"
	PetBreedRussianToy                     PetBreed = "Russian Toy"
	PetBreedRussianSpaniel                 PetBreed = "Russian Spaniel"
	PetBreedRussianTsvetnayaBolonka        PetBreed = "Russian Tsvetnaya Bolonka"
	PetBreedRomanianMioriticShepherdDog    PetBreed = "Romanian Mioritic Shepherd Dog"
	PetBreedRajapalayam                    PetBreed = "Rajapalayam"
	PetBreedRafeirodoAlentejo              PetBreed = "Rafeiro do Alentejo"
	PetBreedSiberianHusky                  PetBreed = "Siberian Husky"
	PetBreedShihTzu                        PetBreed = "Shih Tzu"
	PetBreedShetlandSheepdog               PetBreed = "Shetland Sheepdog"
	PetBreedShibaInu                       PetBreed = "Shiba Inu"
	PetBreedStBernard                      PetBreed = "St. Bernard"
	PetBreedSamoyed                        PetBreed = "Samoyed"
	PetBreedScottishTerrier                PetBreed = "Scottish Terrier"
	PetBreedSoftCoatedWheatenTerrier       PetBreed = "Soft Coated Wheaten Terrier"
	PetBreedSharPei                        PetBreed = "Shar-Pei"
	PetBreedStaffordshireBullTerrier       PetBreed = "Staffordshire Bull Terrier"
	PetBreedStandardSchnauzer              PetBreed = "Standard Schnauzer"
	PetBreedSilkyTerrier                   PetBreed = "Silky Terrier"
	PetBreedSpinoneItaliano                PetBreed = "Spinone Italiano"
	PetBreedSchipperke                     PetBreed = "Schipperke"
	PetBreedSmoothFoxTerrier               PetBreed = "Smooth Fox Terrier"
	PetBreedSaluki                         PetBreed = "Saluki"
	PetBreedSwedishVallhund                PetBreed = "Swedish Vallhund"
	PetBreedSealyhamTerrier                PetBreed = "Sealyham Terrier"
	PetBreedSpanishWaterDog                PetBreed = "Spanish Water Dog"
	PetBreedScottishDeerhound              PetBreed = "Scottish Deerhound"
	PetBreedSussexSpaniel                  PetBreed = "Sussex Spaniel"
	PetBreedSkyeTerrier                    PetBreed = "Skye Terrier"
	PetBreedSloughi                        PetBreed = "Sloughi"
	PetBreedSmallMunsterlander             PetBreed = "Small Munsterlander"
	PetBreedSaarloosWolfdog                PetBreed = "Saarloos Wolfdog"
	PetBreedSarplaninac                    PetBreed = "Sarplaninac"
	PetBreedSchapendoes                    PetBreed = "Schapendoes"
	PetBreedShikoku                        PetBreed = "Shikoku"
	PetBreedShilohShepherd                 PetBreed = "Shiloh Shepherd"
	PetBreedSilkenWindhound                PetBreed = "Silken Windhound"
	PetBreedSpanishMastiff                 PetBreed = "Spanish Mastiff"
	PetBreedSwedishLapphund                PetBreed = "Swedish Lapphund"
	PetBreedShichon                        PetBreed = "Shichon"
	PetBreedSlovenskyCuvac                 PetBreed = "Slovensky Cuvac"
	PetBreedStabyhoun                      PetBreed = "Stabyhoun"
	PetBreedSpanishGreyhound               PetBreed = "Spanish Greyhound"
	PetBreedSeppalaSiberianSleddog         PetBreed = "Seppala Siberian Sleddog"
	PetBreedSouthRussianOvcharka           PetBreed = "South Russian Ovcharka"
	PetBreedSapsali                        PetBreed = "Sapsali"
	PetBreedSmalandHound                   PetBreed = "Smaland Hound"
	PetBreedSerbianHound                   PetBreed = "Serbian Hound"
	PetBreedTibetanTerrier                 PetBreed = "Tibetan Terrier"
	PetBreedToyFoxTerrier                  PetBreed = "Toy Fox Terrier"
	PetBreedTibetanSpaniel                 PetBreed = "Tibetan Spaniel"
	PetBreedTibetanMastiff                 PetBreed = "Tibetan Mastiff"
	PetBreedTreeingWalkerCoonhound         PetBreed = "Treeing Walker Coonhound"
	PetBreedToyPoodle                      PetBreed = "Toy Poodle"
	PetBreedTamaskanDog                    PetBreed = "Tamaskan Dog"
	PetBreedThaiRidgeback                  PetBreed = "Thai Ridgeback"
	PetBreedTosaKen                        PetBreed = "Tosa Ken"
	PetBreedTexasHeeler                    PetBreed = "Texas Heeler"
	PetBreedTornjak                        PetBreed = "Tornjak"
	PetBreedTacoTerrier                    PetBreed = "Taco Terrier"
	PetBreedThaiBangkaewDog                PetBreed = "Thai Bangkaew Dog"
	PetBreedTransylvanianHound             PetBreed = "Transylvanian Hound"
	PetBreedVizsla                         PetBreed = "Vizsla"
	PetBreedVolpinoItaliano                PetBreed = "Volpino Italiano"
	PetBreedWeimaraner                     PetBreed = "Weimaraner"
	PetBreedWestHighlandWhiteTerrier       PetBreed = "West Highland White Terrier"
	PetBreedWhippet                        PetBreed = "Whippet"
	PetBreedWirehairedPointingGriffon      PetBreed = "Wirehaired Pointing Griffon"
	PetBreedWireFoxTerrier                 PetBreed = "Wire Fox Terrier"
	PetBreedWelshTerrier                   PetBreed = "Welsh Terrier"
	PetBreedWelshSpringerSpaniel           PetBreed = "Welsh Springer Spaniel"
	PetBreedWirehairedVizsla               PetBreed = "Wirehaired Vizsla"
	PetBreedWestSiberianLaika              PetBreed = "West Siberian Laika"
	PetBreedWetterhoun                     PetBreed = "Wetterhoun"
	PetBreedXoloitzcuintli                 PetBreed = "Xoloitzcuintli"
	PetBreedYorkshireTerrier               PetBreed = "Yorkshire Terrier"
)

func (e *PetBreed) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetBreed(s)
	case string:
		*e = PetBreed(s)
	default:
		return fmt.Errorf("unsupported scan type for PetBreed: %T", src)
	}
	return nil
}

type NullPetBreed struct {
	PetBreed PetBreed `json:"petBreed"`
	Valid    bool     `json:"valid"` // Valid is true if PetBreed is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetBreed) Scan(value interface{}) error {
	if value == nil {
		ns.PetBreed, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetBreed.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetBreed) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetBreed), nil
}

func (e PetBreed) Valid() bool {
	switch e {
	case PetBreedAustralianShepherd,
		PetBreedAmericanCockerSpaniel,
		PetBreedAkita,
		PetBreedAustralianCattle,
		PetBreedAiredaleTerrier,
		PetBreedAlaskanMalamute,
		PetBreedAmericanStaffordshireTerrier,
		PetBreedAnatolianShepherd,
		PetBreedAmericanEskimo,
		PetBreedAfghanHound,
		PetBreedAmericanHairlessTerrier,
		PetBreedAustralianTerrier,
		PetBreedAmericanWaterSpaniel,
		PetBreedAffenpinscher,
		PetBreedAmericanEnglishCoonhound,
		PetBreedAmericanFoxhound,
		PetBreedAzawakh,
		PetBreedAmericanPitBullTerrier,
		PetBreedAmericanWhiteShepherd,
		PetBreedAlapahaBlueBloodBulldog,
		PetBreedAlaskanKleeKai,
		PetBreedAppenzellerSennenhund,
		PetBreedAustralianBulldog,
		PetBreedAustralianKelpie,
		PetBreedAustralianStumpyTailCattle,
		PetBreedAustrianBlackandTanHound,
		PetBreedAustrianPinscher,
		PetBreedAlaskanHusky,
		PetBreedAmericanBulldog,
		PetBreedAndalusianHound,
		PetBreedAmericanMastiff,
		PetBreedAkbash,
		PetBreedAlanoEspanol,
		PetBreedAriegePointer,
		PetBreedAriegeois,
		PetBreedAfricanis,
		PetBreedAidi,
		PetBreedAmericanStaghound,
		PetBreedAlopekis,
		PetBreedBulldog,
		PetBreedBeagle,
		PetBreedBoxer,
		PetBreedBostonTerrier,
		PetBreedBerneseMountain,
		PetBreedBrittany,
		PetBreedBorderCollie,
		PetBreedBassetHound,
		PetBreedBelgianMalinois,
		PetBreedBichonFrise,
		PetBreedBloodhound,
		PetBreedBullmastiff,
		PetBreedBullTerrier,
		PetBreedBasenji,
		PetBreedBoykinSpaniel,
		PetBreedBrusselsGriffon,
		PetBreedBouvierdesFlandres,
		PetBreedBorderTerrier,
		PetBreedBorzoi,
		PetBreedBelgianTervuren,
		PetBreedBelgianSheep,
		PetBreedBeauceron,
		PetBreedBoerboel,
		PetBreedBeardedCollie,
		PetBreedBlackRussianTerrier,
		PetBreedBlackandTanCoonhound,
		PetBreedBluetickCoonhound,
		PetBreedBedlingtonTerrier,
		PetBreedBarbet,
		PetBreedBriard,
		PetBreedBergerPicard,
		PetBreedBergamasco,
		PetBreedBolognese,
		PetBreedBassetBleudeGascogne,
		PetBreedBassetFauvedeBretagne,
		PetBreedBelgianShepherdLaekenois,
		PetBreedBlackMouthCur,
		PetBreedBlackNorwegianElkhound,
		PetBreedBlueLacy,
		PetBreedBluePicardySpaniel,
		PetBreedBohemianShepherd,
		PetBreedBraccoItaliano,
		PetBreedBraqueduBourbonnais,
		PetBreedBrazilianTerrier,
		PetBreedBulgarianShepherd,
		PetBreedBassetArtesienNormand,
		PetBreedBroholmer,
		PetBreedBiewerTerrier,
		PetBreedBriquetGriffonVendeen,
		PetBreedBukovinaSheepdog,
		PetBreedBeagleHarrier,
		PetBreedBeaglier,
		PetBreedBavarianMountainHound,
		PetBreedBouvierdesArdennes,
		PetBreedBullArab,
		PetBreedCavalierKingCharlesSpaniel,
		PetBreedCaneCorso,
		PetBreedChihuahua,
		PetBreedCollie,
		PetBreedChesapeakeBayRetriever,
		PetBreedCardiganWelshCorgi,
		PetBreedCairnTerrier,
		PetBreedChineseCrested,
		PetBreedCotonDeTulear,
		PetBreedChowChow,
		PetBreedClumberSpaniel,
		PetBreedCurlyCoatedRetriever,
		PetBreedCirnecodellEtna,
		PetBreedCanaan,
		PetBreedChinook,
		PetBreedCeskyTerrier,
		PetBreedCockapoo,
		PetBreedCanadianEskimo,
		PetBreedCarolina,
		PetBreedCarpathianSheepdog,
		PetBreedCatahoulaBulldog,
		PetBreedCatahoulaLeopard,
		PetBreedCatalanSheepdog,
		PetBreedCaucasianOvcharka,
		PetBreedCentralAsianOvtcharka,
		PetBreedCroatianSheepdog,
		PetBreedCzechoslovakianWolfdog,
		PetBreedCeskyFousek,
		PetBreedChartPolski,
		PetBreedCairmal,
		PetBreedChorkie,
		PetBreedCockalier,
		PetBreedCaravanHound,
		PetBreedCodaSerradeAires,
		PetBreedChippiparai,
		PetBreedChizer,
		PetBreedCotonese,
		PetBreedDachshund,
		PetBreedDobermanPinscher,
		PetBreedDalmatian,
		PetBreedDoguedeBordeaux,
		PetBreedDogoArgentino,
		PetBreedDandieDinmontTerrier,
		PetBreedDutchShepherd,
		PetBreedDoubleDoodle,
		PetBreedDeutscheBracke,
		PetBreedDorkie,
		PetBreedDanishSwedishFarmdog,
		PetBreedDingo,
		PetBreedDutchSmoushond,
		PetBreedDrentsePatrijshond,
		PetBreedDrever,
		PetBreedDunker,
		PetBreedDorgi,
		PetBreedEnglishSpringerSpaniel,
		PetBreedEnglishCockerSpaniel,
		PetBreedEnglishSetter,
		PetBreedEnglishToySpaniel,
		PetBreedEntlebucherMountain,
		PetBreedEnglishFoxhound,
		PetBreedEastEuropeanShepherd,
		PetBreedEnglishShepherd,
		PetBreedEurasier,
		PetBreedEastSiberianLaika,
		PetBreedFrenchBulldog,
		PetBreedFlatCoatedRetriever,
		PetBreedFieldSpaniel,
		PetBreedFinnishLapphund,
		PetBreedFinnishSpitz,
		PetBreedFilaBrasileiro,
		PetBreedFrenchSpaniel,
		PetBreedFinnishHound,
		PetBreedFrancaisBlancetNoir,
		PetBreedGermanShepherd,
		PetBreedGoldenRetriever,
		PetBreedGermanShorthairedPointer,
		PetBreedGreatDane,
		PetBreedGermanWirehairedPointer,
		PetBreedGiantSchnauzer,
		PetBreedGreatPyrenees,
		PetBreedGreaterSwissMountain,
		PetBreedGordonSetter,
		PetBreedGermanPinscher,
		PetBreedGreyhound,
		PetBreedGlenofImaalTerrier,
		PetBreedGrandBassetGriffonVendeen,
		PetBreedGoldendoodle,
		PetBreedGermanLonghairedPointer,
		PetBreedGreenland,
		PetBreedGriffonbleudeGascogne,
		PetBreedGrandBleudeGascogne,
		PetBreedHavanese,
		PetBreedHarrier,
		PetBreedHokkaido,
		PetBreedHovawart,
		PetBreedHamiltonHound,
		PetBreedItalianGreyhound,
		PetBreedIrishWolfhound,
		PetBreedIrishSetter,
		PetBreedIrishTerrier,
		PetBreedIcelandicSheepdog,
		PetBreedIrishRedandWhiteSetter,
		PetBreedIbizanHound,
		PetBreedIrishWaterSpaniel,
		PetBreedJackRussellTerrier,
		PetBreedJapaneseChin,
		PetBreedJapaneseSpitz,
		PetBreedJagdterrier,
		PetBreedJapaneseTerrier,
		PetBreedJmthund,
		PetBreedKeeshond,
		PetBreedKerryBlueTerrier,
		PetBreedKooikerhondje,
		PetBreedKuvasz,
		PetBreedKomondor,
		PetBreedKoreanJindo,
		PetBreedKarelianBear,
		PetBreedKishuKen,
		PetBreedKoolie,
		PetBreedKromfohrlander,
		PetBreedKangal,
		PetBreedKingShepherd,
		PetBreedKyiLeo,
		PetBreedKarstShepherd,
		PetBreedLabradorRetriever,
		PetBreedLhasaApso,
		PetBreedLagottoRomagnolo,
		PetBreedLeonberger,
		PetBreedLakelandTerrier,
		PetBreedLowchen,
		PetBreedLargeMunsterlander,
		PetBreedLancashireHeeler,
		PetBreedLandseer,
		PetBreedLucasTerrier,
		PetBreedLurcher,
		PetBreedLapponianHerder,
		PetBreedMiniatureSchnauzer,
		PetBreedMiniatureAmericanShepherd,
		PetBreedMastiff,
		PetBreedMaltese,
		PetBreedMiniaturePinscher,
		PetBreedMiniatureBullTerrier,
		PetBreedManchesterTerrier,
		PetBreedMiniatureBulldog,
		PetBreedMiniaturePoodle,
		PetBreedMiniatureSharPei,
		PetBreedMcNab,
		PetBreedMudi,
		PetBreedMountainFeist,
		PetBreedMaremmaSheepdog,
		PetBreedMalShi,
		PetBreedMoscowWatchdog,
		PetBreedMountainCur,
		PetBreedMajesticTreeHound,
		PetBreedNewfoundland,
		PetBreedNovaScotiaDuckTollingRetriever,
		PetBreedNorwegianElkhound,
		PetBreedNeapolitanMastiff,
		PetBreedNorwichTerrier,
		PetBreedNorfolkTerrier,
		PetBreedNorwegianBuhund,
		PetBreedNorwegianLundehund,
		PetBreedNorrbottenspets,
		PetBreedNorthernInuit,
		PetBreedNewGuineaSinging,
		PetBreedOldEnglishSheepdog,
		PetBreedOtterhound,
		PetBreedOldeEnglishBulldogge,
		PetBreedPoodle,
		PetBreedPembrokeWelshCorgi,
		PetBreedPomeranian,
		PetBreedPug,
		PetBreedPortugueseWater,
		PetBreedPapillon,
		PetBreedPekingese,
		PetBreedParsonRussellTerrier,
		PetBreedPointer,
		PetBreedPuli,
		PetBreedPumi,
		PetBreedPortuguesePodengoPequeno,
		PetBreedPetitBassetGriffonVendeen,
		PetBreedPlottHound,
		PetBreedPolishLowlandSheepdog,
		PetBreedPharaohHound,
		PetBreedPyreneanShepherd,
		PetBreedPakistaniMastiff,
		PetBreedPatterdaleTerrier,
		PetBreedPerrodePresaCanario,
		PetBreedPerrodePresaMallorquin,
		PetBreedPeruvianIncaOrchid,
		PetBreedPicardySpaniel,
		PetBreedPrazskyKrysarik,
		PetBreedPontAudemerSpaniel,
		PetBreedPyreneanMastiff,
		PetBreedPolishTatraSheepdog,
		PetBreedPuggle,
		PetBreedPudelpointer,
		PetBreedPlummerTerrier,
		PetBreedPortuguesePointer,
		PetBreedPolishHuntingDog,
		PetBreedRottweiler,
		PetBreedRhodesianRidgeback,
		PetBreedRatTerrier,
		PetBreedRedboneCoonhound,
		PetBreedRussianToy,
		PetBreedRussianSpaniel,
		PetBreedRussianTsvetnayaBolonka,
		PetBreedRomanianMioriticShepherdDog,
		PetBreedRajapalayam,
		PetBreedRafeirodoAlentejo,
		PetBreedSiberianHusky,
		PetBreedShihTzu,
		PetBreedShetlandSheepdog,
		PetBreedShibaInu,
		PetBreedStBernard,
		PetBreedSamoyed,
		PetBreedScottishTerrier,
		PetBreedSoftCoatedWheatenTerrier,
		PetBreedSharPei,
		PetBreedStaffordshireBullTerrier,
		PetBreedStandardSchnauzer,
		PetBreedSilkyTerrier,
		PetBreedSpinoneItaliano,
		PetBreedSchipperke,
		PetBreedSmoothFoxTerrier,
		PetBreedSaluki,
		PetBreedSwedishVallhund,
		PetBreedSealyhamTerrier,
		PetBreedSpanishWaterDog,
		PetBreedScottishDeerhound,
		PetBreedSussexSpaniel,
		PetBreedSkyeTerrier,
		PetBreedSloughi,
		PetBreedSmallMunsterlander,
		PetBreedSaarloosWolfdog,
		PetBreedSarplaninac,
		PetBreedSchapendoes,
		PetBreedShikoku,
		PetBreedShilohShepherd,
		PetBreedSilkenWindhound,
		PetBreedSpanishMastiff,
		PetBreedSwedishLapphund,
		PetBreedShichon,
		PetBreedSlovenskyCuvac,
		PetBreedStabyhoun,
		PetBreedSpanishGreyhound,
		PetBreedSeppalaSiberianSleddog,
		PetBreedSouthRussianOvcharka,
		PetBreedSapsali,
		PetBreedSmalandHound,
		PetBreedSerbianHound,
		PetBreedTibetanTerrier,
		PetBreedToyFoxTerrier,
		PetBreedTibetanSpaniel,
		PetBreedTibetanMastiff,
		PetBreedTreeingWalkerCoonhound,
		PetBreedToyPoodle,
		PetBreedTamaskanDog,
		PetBreedThaiRidgeback,
		PetBreedTosaKen,
		PetBreedTexasHeeler,
		PetBreedTornjak,
		PetBreedTacoTerrier,
		PetBreedThaiBangkaewDog,
		PetBreedTransylvanianHound,
		PetBreedVizsla,
		PetBreedVolpinoItaliano,
		PetBreedWeimaraner,
		PetBreedWestHighlandWhiteTerrier,
		PetBreedWhippet,
		PetBreedWirehairedPointingGriffon,
		PetBreedWireFoxTerrier,
		PetBreedWelshTerrier,
		PetBreedWelshSpringerSpaniel,
		PetBreedWirehairedVizsla,
		PetBreedWestSiberianLaika,
		PetBreedWetterhoun,
		PetBreedXoloitzcuintli,
		PetBreedYorkshireTerrier:
		return true
	}
	return false
}

func AllPetBreedValues() []PetBreed {
	return []PetBreed{
		PetBreedAustralianShepherd,
		PetBreedAmericanCockerSpaniel,
		PetBreedAkita,
		PetBreedAustralianCattle,
		PetBreedAiredaleTerrier,
		PetBreedAlaskanMalamute,
		PetBreedAmericanStaffordshireTerrier,
		PetBreedAnatolianShepherd,
		PetBreedAmericanEskimo,
		PetBreedAfghanHound,
		PetBreedAmericanHairlessTerrier,
		PetBreedAustralianTerrier,
		PetBreedAmericanWaterSpaniel,
		PetBreedAffenpinscher,
		PetBreedAmericanEnglishCoonhound,
		PetBreedAmericanFoxhound,
		PetBreedAzawakh,
		PetBreedAmericanPitBullTerrier,
		PetBreedAmericanWhiteShepherd,
		PetBreedAlapahaBlueBloodBulldog,
		PetBreedAlaskanKleeKai,
		PetBreedAppenzellerSennenhund,
		PetBreedAustralianBulldog,
		PetBreedAustralianKelpie,
		PetBreedAustralianStumpyTailCattle,
		PetBreedAustrianBlackandTanHound,
		PetBreedAustrianPinscher,
		PetBreedAlaskanHusky,
		PetBreedAmericanBulldog,
		PetBreedAndalusianHound,
		PetBreedAmericanMastiff,
		PetBreedAkbash,
		PetBreedAlanoEspanol,
		PetBreedAriegePointer,
		PetBreedAriegeois,
		PetBreedAfricanis,
		PetBreedAidi,
		PetBreedAmericanStaghound,
		PetBreedAlopekis,
		PetBreedBulldog,
		PetBreedBeagle,
		PetBreedBoxer,
		PetBreedBostonTerrier,
		PetBreedBerneseMountain,
		PetBreedBrittany,
		PetBreedBorderCollie,
		PetBreedBassetHound,
		PetBreedBelgianMalinois,
		PetBreedBichonFrise,
		PetBreedBloodhound,
		PetBreedBullmastiff,
		PetBreedBullTerrier,
		PetBreedBasenji,
		PetBreedBoykinSpaniel,
		PetBreedBrusselsGriffon,
		PetBreedBouvierdesFlandres,
		PetBreedBorderTerrier,
		PetBreedBorzoi,
		PetBreedBelgianTervuren,
		PetBreedBelgianSheep,
		PetBreedBeauceron,
		PetBreedBoerboel,
		PetBreedBeardedCollie,
		PetBreedBlackRussianTerrier,
		PetBreedBlackandTanCoonhound,
		PetBreedBluetickCoonhound,
		PetBreedBedlingtonTerrier,
		PetBreedBarbet,
		PetBreedBriard,
		PetBreedBergerPicard,
		PetBreedBergamasco,
		PetBreedBolognese,
		PetBreedBassetBleudeGascogne,
		PetBreedBassetFauvedeBretagne,
		PetBreedBelgianShepherdLaekenois,
		PetBreedBlackMouthCur,
		PetBreedBlackNorwegianElkhound,
		PetBreedBlueLacy,
		PetBreedBluePicardySpaniel,
		PetBreedBohemianShepherd,
		PetBreedBraccoItaliano,
		PetBreedBraqueduBourbonnais,
		PetBreedBrazilianTerrier,
		PetBreedBulgarianShepherd,
		PetBreedBassetArtesienNormand,
		PetBreedBroholmer,
		PetBreedBiewerTerrier,
		PetBreedBriquetGriffonVendeen,
		PetBreedBukovinaSheepdog,
		PetBreedBeagleHarrier,
		PetBreedBeaglier,
		PetBreedBavarianMountainHound,
		PetBreedBouvierdesArdennes,
		PetBreedBullArab,
		PetBreedCavalierKingCharlesSpaniel,
		PetBreedCaneCorso,
		PetBreedChihuahua,
		PetBreedCollie,
		PetBreedChesapeakeBayRetriever,
		PetBreedCardiganWelshCorgi,
		PetBreedCairnTerrier,
		PetBreedChineseCrested,
		PetBreedCotonDeTulear,
		PetBreedChowChow,
		PetBreedClumberSpaniel,
		PetBreedCurlyCoatedRetriever,
		PetBreedCirnecodellEtna,
		PetBreedCanaan,
		PetBreedChinook,
		PetBreedCeskyTerrier,
		PetBreedCockapoo,
		PetBreedCanadianEskimo,
		PetBreedCarolina,
		PetBreedCarpathianSheepdog,
		PetBreedCatahoulaBulldog,
		PetBreedCatahoulaLeopard,
		PetBreedCatalanSheepdog,
		PetBreedCaucasianOvcharka,
		PetBreedCentralAsianOvtcharka,
		PetBreedCroatianSheepdog,
		PetBreedCzechoslovakianWolfdog,
		PetBreedCeskyFousek,
		PetBreedChartPolski,
		PetBreedCairmal,
		PetBreedChorkie,
		PetBreedCockalier,
		PetBreedCaravanHound,
		PetBreedCodaSerradeAires,
		PetBreedChippiparai,
		PetBreedChizer,
		PetBreedCotonese,
		PetBreedDachshund,
		PetBreedDobermanPinscher,
		PetBreedDalmatian,
		PetBreedDoguedeBordeaux,
		PetBreedDogoArgentino,
		PetBreedDandieDinmontTerrier,
		PetBreedDutchShepherd,
		PetBreedDoubleDoodle,
		PetBreedDeutscheBracke,
		PetBreedDorkie,
		PetBreedDanishSwedishFarmdog,
		PetBreedDingo,
		PetBreedDutchSmoushond,
		PetBreedDrentsePatrijshond,
		PetBreedDrever,
		PetBreedDunker,
		PetBreedDorgi,
		PetBreedEnglishSpringerSpaniel,
		PetBreedEnglishCockerSpaniel,
		PetBreedEnglishSetter,
		PetBreedEnglishToySpaniel,
		PetBreedEntlebucherMountain,
		PetBreedEnglishFoxhound,
		PetBreedEastEuropeanShepherd,
		PetBreedEnglishShepherd,
		PetBreedEurasier,
		PetBreedEastSiberianLaika,
		PetBreedFrenchBulldog,
		PetBreedFlatCoatedRetriever,
		PetBreedFieldSpaniel,
		PetBreedFinnishLapphund,
		PetBreedFinnishSpitz,
		PetBreedFilaBrasileiro,
		PetBreedFrenchSpaniel,
		PetBreedFinnishHound,
		PetBreedFrancaisBlancetNoir,
		PetBreedGermanShepherd,
		PetBreedGoldenRetriever,
		PetBreedGermanShorthairedPointer,
		PetBreedGreatDane,
		PetBreedGermanWirehairedPointer,
		PetBreedGiantSchnauzer,
		PetBreedGreatPyrenees,
		PetBreedGreaterSwissMountain,
		PetBreedGordonSetter,
		PetBreedGermanPinscher,
		PetBreedGreyhound,
		PetBreedGlenofImaalTerrier,
		PetBreedGrandBassetGriffonVendeen,
		PetBreedGoldendoodle,
		PetBreedGermanLonghairedPointer,
		PetBreedGreenland,
		PetBreedGriffonbleudeGascogne,
		PetBreedGrandBleudeGascogne,
		PetBreedHavanese,
		PetBreedHarrier,
		PetBreedHokkaido,
		PetBreedHovawart,
		PetBreedHamiltonHound,
		PetBreedItalianGreyhound,
		PetBreedIrishWolfhound,
		PetBreedIrishSetter,
		PetBreedIrishTerrier,
		PetBreedIcelandicSheepdog,
		PetBreedIrishRedandWhiteSetter,
		PetBreedIbizanHound,
		PetBreedIrishWaterSpaniel,
		PetBreedJackRussellTerrier,
		PetBreedJapaneseChin,
		PetBreedJapaneseSpitz,
		PetBreedJagdterrier,
		PetBreedJapaneseTerrier,
		PetBreedJmthund,
		PetBreedKeeshond,
		PetBreedKerryBlueTerrier,
		PetBreedKooikerhondje,
		PetBreedKuvasz,
		PetBreedKomondor,
		PetBreedKoreanJindo,
		PetBreedKarelianBear,
		PetBreedKishuKen,
		PetBreedKoolie,
		PetBreedKromfohrlander,
		PetBreedKangal,
		PetBreedKingShepherd,
		PetBreedKyiLeo,
		PetBreedKarstShepherd,
		PetBreedLabradorRetriever,
		PetBreedLhasaApso,
		PetBreedLagottoRomagnolo,
		PetBreedLeonberger,
		PetBreedLakelandTerrier,
		PetBreedLowchen,
		PetBreedLargeMunsterlander,
		PetBreedLancashireHeeler,
		PetBreedLandseer,
		PetBreedLucasTerrier,
		PetBreedLurcher,
		PetBreedLapponianHerder,
		PetBreedMiniatureSchnauzer,
		PetBreedMiniatureAmericanShepherd,
		PetBreedMastiff,
		PetBreedMaltese,
		PetBreedMiniaturePinscher,
		PetBreedMiniatureBullTerrier,
		PetBreedManchesterTerrier,
		PetBreedMiniatureBulldog,
		PetBreedMiniaturePoodle,
		PetBreedMiniatureSharPei,
		PetBreedMcNab,
		PetBreedMudi,
		PetBreedMountainFeist,
		PetBreedMaremmaSheepdog,
		PetBreedMalShi,
		PetBreedMoscowWatchdog,
		PetBreedMountainCur,
		PetBreedMajesticTreeHound,
		PetBreedNewfoundland,
		PetBreedNovaScotiaDuckTollingRetriever,
		PetBreedNorwegianElkhound,
		PetBreedNeapolitanMastiff,
		PetBreedNorwichTerrier,
		PetBreedNorfolkTerrier,
		PetBreedNorwegianBuhund,
		PetBreedNorwegianLundehund,
		PetBreedNorrbottenspets,
		PetBreedNorthernInuit,
		PetBreedNewGuineaSinging,
		PetBreedOldEnglishSheepdog,
		PetBreedOtterhound,
		PetBreedOldeEnglishBulldogge,
		PetBreedPoodle,
		PetBreedPembrokeWelshCorgi,
		PetBreedPomeranian,
		PetBreedPug,
		PetBreedPortugueseWater,
		PetBreedPapillon,
		PetBreedPekingese,
		PetBreedParsonRussellTerrier,
		PetBreedPointer,
		PetBreedPuli,
		PetBreedPumi,
		PetBreedPortuguesePodengoPequeno,
		PetBreedPetitBassetGriffonVendeen,
		PetBreedPlottHound,
		PetBreedPolishLowlandSheepdog,
		PetBreedPharaohHound,
		PetBreedPyreneanShepherd,
		PetBreedPakistaniMastiff,
		PetBreedPatterdaleTerrier,
		PetBreedPerrodePresaCanario,
		PetBreedPerrodePresaMallorquin,
		PetBreedPeruvianIncaOrchid,
		PetBreedPicardySpaniel,
		PetBreedPrazskyKrysarik,
		PetBreedPontAudemerSpaniel,
		PetBreedPyreneanMastiff,
		PetBreedPolishTatraSheepdog,
		PetBreedPuggle,
		PetBreedPudelpointer,
		PetBreedPlummerTerrier,
		PetBreedPortuguesePointer,
		PetBreedPolishHuntingDog,
		PetBreedRottweiler,
		PetBreedRhodesianRidgeback,
		PetBreedRatTerrier,
		PetBreedRedboneCoonhound,
		PetBreedRussianToy,
		PetBreedRussianSpaniel,
		PetBreedRussianTsvetnayaBolonka,
		PetBreedRomanianMioriticShepherdDog,
		PetBreedRajapalayam,
		PetBreedRafeirodoAlentejo,
		PetBreedSiberianHusky,
		PetBreedShihTzu,
		PetBreedShetlandSheepdog,
		PetBreedShibaInu,
		PetBreedStBernard,
		PetBreedSamoyed,
		PetBreedScottishTerrier,
		PetBreedSoftCoatedWheatenTerrier,
		PetBreedSharPei,
		PetBreedStaffordshireBullTerrier,
		PetBreedStandardSchnauzer,
		PetBreedSilkyTerrier,
		PetBreedSpinoneItaliano,
		PetBreedSchipperke,
		PetBreedSmoothFoxTerrier,
		PetBreedSaluki,
		PetBreedSwedishVallhund,
		PetBreedSealyhamTerrier,
		PetBreedSpanishWaterDog,
		PetBreedScottishDeerhound,
		PetBreedSussexSpaniel,
		PetBreedSkyeTerrier,
		PetBreedSloughi,
		PetBreedSmallMunsterlander,
		PetBreedSaarloosWolfdog,
		PetBreedSarplaninac,
		PetBreedSchapendoes,
		PetBreedShikoku,
		PetBreedShilohShepherd,
		PetBreedSilkenWindhound,
		PetBreedSpanishMastiff,
		PetBreedSwedishLapphund,
		PetBreedShichon,
		PetBreedSlovenskyCuvac,
		PetBreedStabyhoun,
		PetBreedSpanishGreyhound,
		PetBreedSeppalaSiberianSleddog,
		PetBreedSouthRussianOvcharka,
		PetBreedSapsali,
		PetBreedSmalandHound,
		PetBreedSerbianHound,
		PetBreedTibetanTerrier,
		PetBreedToyFoxTerrier,
		PetBreedTibetanSpaniel,
		PetBreedTibetanMastiff,
		PetBreedTreeingWalkerCoonhound,
		PetBreedToyPoodle,
		PetBreedTamaskanDog,
		PetBreedThaiRidgeback,
		PetBreedTosaKen,
		PetBreedTexasHeeler,
		PetBreedTornjak,
		PetBreedTacoTerrier,
		PetBreedThaiBangkaewDog,
		PetBreedTransylvanianHound,
		PetBreedVizsla,
		PetBreedVolpinoItaliano,
		PetBreedWeimaraner,
		PetBreedWestHighlandWhiteTerrier,
		PetBreedWhippet,
		PetBreedWirehairedPointingGriffon,
		PetBreedWireFoxTerrier,
		PetBreedWelshTerrier,
		PetBreedWelshSpringerSpaniel,
		PetBreedWirehairedVizsla,
		PetBreedWestSiberianLaika,
		PetBreedWetterhoun,
		PetBreedXoloitzcuintli,
		PetBreedYorkshireTerrier,
	}
}

type PetInteraction string

const (
	PetInteractionLovesotherdogs              PetInteraction = "Loves other dogs"
	PetInteractionPrefershumancompany         PetInteraction = "Prefers human company"
	PetInteractionGoodwithchildren            PetInteraction = "Good with children"
	PetInteractionGoodwithcatsOtherpets       PetInteraction = "Good with cats/other pets"
	PetInteractionEnjoyslargegroups           PetInteraction = "Enjoys large groups"
	PetInteractionPrefersoneOnOneinteractions PetInteraction = "Prefers one-on-one interactions"
)

func (e *PetInteraction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetInteraction(s)
	case string:
		*e = PetInteraction(s)
	default:
		return fmt.Errorf("unsupported scan type for PetInteraction: %T", src)
	}
	return nil
}

type NullPetInteraction struct {
	PetInteraction PetInteraction `json:"petInteraction"`
	Valid          bool           `json:"valid"` // Valid is true if PetInteraction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetInteraction) Scan(value interface{}) error {
	if value == nil {
		ns.PetInteraction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetInteraction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetInteraction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetInteraction), nil
}

func (e PetInteraction) Valid() bool {
	switch e {
	case PetInteractionLovesotherdogs,
		PetInteractionPrefershumancompany,
		PetInteractionGoodwithchildren,
		PetInteractionGoodwithcatsOtherpets,
		PetInteractionEnjoyslargegroups,
		PetInteractionPrefersoneOnOneinteractions:
		return true
	}
	return false
}

func AllPetInteractionValues() []PetInteraction {
	return []PetInteraction{
		PetInteractionLovesotherdogs,
		PetInteractionPrefershumancompany,
		PetInteractionGoodwithchildren,
		PetInteractionGoodwithcatsOtherpets,
		PetInteractionEnjoyslargegroups,
		PetInteractionPrefersoneOnOneinteractions,
	}
}

type PetPersonality string

const (
	PetPersonalityPlayful      PetPersonality = "Playful"
	PetPersonalityEnergetic    PetPersonality = "Energetic"
	PetPersonalityShy          PetPersonality = "Shy"
	PetPersonalityOutgoing     PetPersonality = "Outgoing"
	PetPersonalityCalm         PetPersonality = "Calm"
	PetPersonalityReserved     PetPersonality = "Reserved"
	PetPersonalityAffectionate PetPersonality = "Affectionate"
	PetPersonalityIndependent  PetPersonality = "Independent"
)

func (e *PetPersonality) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetPersonality(s)
	case string:
		*e = PetPersonality(s)
	default:
		return fmt.Errorf("unsupported scan type for PetPersonality: %T", src)
	}
	return nil
}

type NullPetPersonality struct {
	PetPersonality PetPersonality `json:"petPersonality"`
	Valid          bool           `json:"valid"` // Valid is true if PetPersonality is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetPersonality) Scan(value interface{}) error {
	if value == nil {
		ns.PetPersonality, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetPersonality.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetPersonality) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetPersonality), nil
}

func (e PetPersonality) Valid() bool {
	switch e {
	case PetPersonalityPlayful,
		PetPersonalityEnergetic,
		PetPersonalityShy,
		PetPersonalityOutgoing,
		PetPersonalityCalm,
		PetPersonalityReserved,
		PetPersonalityAffectionate,
		PetPersonalityIndependent:
		return true
	}
	return false
}

func AllPetPersonalityValues() []PetPersonality {
	return []PetPersonality{
		PetPersonalityPlayful,
		PetPersonalityEnergetic,
		PetPersonalityShy,
		PetPersonalityOutgoing,
		PetPersonalityCalm,
		PetPersonalityReserved,
		PetPersonalityAffectionate,
		PetPersonalityIndependent,
	}
}

type PetReactivity string

const (
	PetReactivityNonReactive                  PetReactivity = "Non-reactive"
	PetReactivityReactivetostrangers          PetReactivity = "Reactive to strangers"
	PetReactivityReactivetonoises             PetReactivity = "Reactive to noises"
	PetReactivityReactivetomovingobjects      PetReactivity = "Reactive to moving objects"
	PetReactivityReactivetospecificsituations PetReactivity = "Reactive to specific situations"
	PetReactivityReactivetosamegenderdogs     PetReactivity = "Reactive to same gender dogs"
)

func (e *PetReactivity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetReactivity(s)
	case string:
		*e = PetReactivity(s)
	default:
		return fmt.Errorf("unsupported scan type for PetReactivity: %T", src)
	}
	return nil
}

type NullPetReactivity struct {
	PetReactivity PetReactivity `json:"petReactivity"`
	Valid         bool          `json:"valid"` // Valid is true if PetReactivity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetReactivity) Scan(value interface{}) error {
	if value == nil {
		ns.PetReactivity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetReactivity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetReactivity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetReactivity), nil
}

func (e PetReactivity) Valid() bool {
	switch e {
	case PetReactivityNonReactive,
		PetReactivityReactivetostrangers,
		PetReactivityReactivetonoises,
		PetReactivityReactivetomovingobjects,
		PetReactivityReactivetospecificsituations,
		PetReactivityReactivetosamegenderdogs:
		return true
	}
	return false
}

func AllPetReactivityValues() []PetReactivity {
	return []PetReactivity{
		PetReactivityNonReactive,
		PetReactivityReactivetostrangers,
		PetReactivityReactivetonoises,
		PetReactivityReactivetomovingobjects,
		PetReactivityReactivetospecificsituations,
		PetReactivityReactivetosamegenderdogs,
	}
}

type PetSize string

const (
	PetSizeSmall  PetSize = "small"
	PetSizeMedium PetSize = "medium"
	PetSizeLarge  PetSize = "large"
)

func (e *PetSize) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetSize(s)
	case string:
		*e = PetSize(s)
	default:
		return fmt.Errorf("unsupported scan type for PetSize: %T", src)
	}
	return nil
}

type NullPetSize struct {
	PetSize PetSize `json:"petSize"`
	Valid   bool    `json:"valid"` // Valid is true if PetSize is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetSize) Scan(value interface{}) error {
	if value == nil {
		ns.PetSize, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetSize.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetSize) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetSize), nil
}

func (e PetSize) Valid() bool {
	switch e {
	case PetSizeSmall,
		PetSizeMedium,
		PetSizeLarge:
		return true
	}
	return false
}

func AllPetSizeValues() []PetSize {
	return []PetSize{
		PetSizeSmall,
		PetSizeMedium,
		PetSizeLarge,
	}
}

type PlaceCategory string

const (
	PlaceCategoryDogpark PlaceCategory = "dog park"
	PlaceCategoryMisc    PlaceCategory = "misc"
)

func (e *PlaceCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaceCategory(s)
	case string:
		*e = PlaceCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaceCategory: %T", src)
	}
	return nil
}

type NullPlaceCategory struct {
	PlaceCategory PlaceCategory `json:"placeCategory"`
	Valid         bool          `json:"valid"` // Valid is true if PlaceCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaceCategory) Scan(value interface{}) error {
	if value == nil {
		ns.PlaceCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaceCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaceCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaceCategory), nil
}

func (e PlaceCategory) Valid() bool {
	switch e {
	case PlaceCategoryDogpark,
		PlaceCategoryMisc:
		return true
	}
	return false
}

func AllPlaceCategoryValues() []PlaceCategory {
	return []PlaceCategory{
		PlaceCategoryDogpark,
		PlaceCategoryMisc,
	}
}

type SubscriptionType string

const (
	SubscriptionTypeActive   SubscriptionType = "active"
	SubscriptionTypeInactive SubscriptionType = "inactive"
	SubscriptionTypeUnknown  SubscriptionType = "unknown"
)

func (e *SubscriptionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionType(s)
	case string:
		*e = SubscriptionType(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionType: %T", src)
	}
	return nil
}

type NullSubscriptionType struct {
	SubscriptionType SubscriptionType `json:"subscriptionType"`
	Valid            bool             `json:"valid"` // Valid is true if SubscriptionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionType) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionType), nil
}

func (e SubscriptionType) Valid() bool {
	switch e {
	case SubscriptionTypeActive,
		SubscriptionTypeInactive,
		SubscriptionTypeUnknown:
		return true
	}
	return false
}

func AllSubscriptionTypeValues() []SubscriptionType {
	return []SubscriptionType{
		SubscriptionTypeActive,
		SubscriptionTypeInactive,
		SubscriptionTypeUnknown,
	}
}

type Pet struct {
	ID        uuid.UUID        `json:"id"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	Name      string           `json:"name"`
	Birthday  time.Time        `json:"birthday"`
	PhotoUrl  string           `json:"photoUrl"`
	Gender    Gender           `json:"gender"`
	Size      PetSize          `json:"size"`
	Weight    decimal.Decimal  `json:"weight"`
}

type PetAttr struct {
	ID           uuid.UUID `json:"id"`
	PetID        uuid.UUID `json:"petID"`
	IsSterilized bool      `json:"isSterilized"`
}

type PetAttrAggressionLevel struct {
	ID              uuid.UUID          `json:"id"`
	PetAttrID       uuid.UUID          `json:"petAttrID"`
	AggressionLevel PetAggressionLevel `json:"aggressionLevel"`
}

type PetAttrAllergy struct {
	ID        uuid.UUID  `json:"id"`
	PetAttrID uuid.UUID  `json:"petAttrID"`
	Allergy   PetAllergy `json:"allergy"`
}

type PetAttrBehavior struct {
	ID        uuid.UUID   `json:"id"`
	PetAttrID uuid.UUID   `json:"petAttrID"`
	Behavior  PetBehavior `json:"behavior"`
}

type PetAttrBreed struct {
	ID        uuid.UUID `json:"id"`
	PetAttrID uuid.UUID `json:"petAttrID"`
	Breed     PetBreed  `json:"breed"`
}

type PetAttrInteraction struct {
	ID          uuid.UUID      `json:"id"`
	PetAttrID   uuid.UUID      `json:"petAttrID"`
	Interaction PetInteraction `json:"interaction"`
}

type PetAttrPersonality struct {
	ID          uuid.UUID      `json:"id"`
	PetAttrID   uuid.UUID      `json:"petAttrID"`
	Personality PetPersonality `json:"personality"`
}

type PetAttrReactivity struct {
	ID         uuid.UUID     `json:"id"`
	PetAttrID  uuid.UUID     `json:"petAttrID"`
	Reactivity PetReactivity `json:"reactivity"`
}

type Place struct {
	ID          uuid.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
	Location    interface{}      `json:"location"`
	GmapsID     string           `json:"gmapsID"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Type        PlaceCategory    `json:"type"`
	WebsiteUrl  string           `json:"websiteUrl"`
	Images      []string         `json:"images"`
}

type PlacesMetadatum struct {
	ID          uuid.UUID `json:"id"`
	PlaceID     uuid.UUID `json:"placeID"`
	City        string    `json:"city"`
	Country     string    `json:"country"`
	FullAddress string    `json:"fullAddress"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	Name         string           `json:"name"`
	ExternalID   string           `json:"externalID"`
	Timezone     string           `json:"timezone"`
	Gender       Gender           `json:"gender"`
	HasOnboarded bool             `json:"hasOnboarded"`
}

type UserNotification struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"userID"`
	Enabled         bool      `json:"enabled"`
	IsRegistered    bool      `json:"isRegistered"`
	DailyEnabled    bool      `json:"dailyEnabled"`
	PlaytimeEnabled bool      `json:"playtimeEnabled"`
}

type UserSubscription struct {
	ID               uuid.UUID        `json:"id"`
	UserID           uuid.UUID        `json:"userID"`
	TrialStartDate   time.Time        `json:"trialStartDate"`
	SubscriptionType SubscriptionType `json:"subscriptionType"`
	IsTrialMode      bool             `json:"isTrialMode"`
}

type UsersPetsLink struct {
	ID          uuid.UUID `json:"id"`
	PetID       uuid.UUID `json:"petID"`
	UserID      uuid.UUID `json:"userID"`
	IsDogOwner  bool      `json:"isDogOwner"`
	IsDogSitter bool      `json:"isDogSitter"`
}
