name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    needs: generate-changelog
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
          cache-dependency-path: ./go.sum
      - name: Build Artifact
        run: |
          mkdir -pv bin
          go build -v -o ./bin/backend-api-linux-x86_64-${{ github.ref_name }} ./cmd/main.go
      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: bin/backend-api-linux-x86_64-${{ github.ref_name }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          release_name: "Release ${{ github.ref_name }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"
